### ISSUE TITLE
meta-file isn't formatted correctly

### ISSUE THREAD

**Issue by nicholas-moskwa** [splicebox/Jutils#4]
Hi,

I am trying to run Jutils with my data, but it seems to be having trouble with the graphing functions. My rMATS was done with 3 replicates per sample.
I think the issue is stemming from the meta-file either not being formatted correctly or the values are not aligned. Jutils works for me on your practice data. The convert-results function works, but all the functions with the meta-file give this error:

Traceback (most recent call last):
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 145, in <module>
    main()
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 138, in main
    run_heatmap_module(args, parser_dict)
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 106, in run_heatmap_module
    plot_heatmap(Path(args.tsv_file), Path(args.meta_file), Path(args.out_dir), args.p_value,
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/heatmap_utils.py", line 54, in plot_heatmap
    sample, cond = line.strip().split('\t')
ValueError: not enough values to unpack (expected 2, got 1)
usage: jutils.py [-h] [--p-value P_VALUE] [--q-value Q_VALUE] [--dpsi DPSI]
jutils.py: error: unrecognized arguments: eatureI
Warning: Both command line and file-specific parameters detected, applied!
As most 6 files are allowed, the program will automatically choose the first 6 files!
Traceback (most recent call last):
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 145, in <module>
    main()
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 141, in main
    run_sashimi_module(args, parser_dict)
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 117, in run_sashimi_module
    sashimi_plot_without_bams(args.tsv_file, args.meta_file, args.gtf, args.group_id,
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/sashimi_utils.py", line 42, in sashimi_plot_without_bams
    id, overlay_level = line.strip().split('\t')
ValueError: not enough values to unpack (expected 2, got 1)
[Uploading 17_meta.tsv…]()
[Uploading rmats_JCEC_results.tsv…]()

**Comment by nicholas-moskwa** [comment]
[17_meta.txt](https://github.com/splicebox/Jutils/files/11052864/17_meta.txt)
[rmats_JCEC_results.txt](https://github.com/splicebox/Jutils/files/11052865/rmats_JCEC_results.txt)

**Comment by edwwlui** [comment]
Hi Nicholas,

Thanks for your question! You are right it's the format issue, the 17_meta.txt should be tab-separated instead of space-separated. Please let me know if there are any more issues.

**Comment by nicholas-moskwa** [comment]
Thank you for getting back to me ed! I did re-examine the meta file and you are right it was double-spaces... I made that change and I was able to make the heatmaps, but Jutils is still not able to make Sashimi plots. 

When I run sashimi get this error:
Traceback (most recent call last):
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 145, in <module>
    main()
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 141, in main
    run_sashimi_module(args, parser_dict)
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/jutils.py", line 117, in run_sashimi_module
    sashimi_plot_without_bams(args.tsv_file, args.meta_file, args.gtf, args.group_id,
  File "/pod/2/ch-lee-lab/labdata/Packages/Jutils/sashimi_utils.py", line 62, in sashimi_plot_without_bams
    for coordinates, k in zip(coordinates_list, [9, 10]):
TypeError: 'NoneType' object is not iterable

Any thoughts? Thanks.
[17_meta_Day2.txt](https://github.com/splicebox/Jutils/files/11101033/17_meta_Day2.txt)

**Comment by edwwlui** [comment]
Hi Nicholas,

Sorry for the delay! The issue has been fixed, it was due to the format of the chr name, e.g., "chrGL456233.1". Thanks for bringing it to our attention.
